/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

interface ExampleProps {
  src: string;
  showMD?: boolean;
}
const Example: React.FC<ExampleProps> = ({ src, showMD }) => {
  const [path, setPath] = useState<string>();
  const router = useRouter();
  const origin =
    typeof window !== "undefined" && window.location.origin
      ? window.location.origin
      : "";

  const address_url = origin + router.asPath;

  useEffect(() => {
    setPath(address_url + src);
  }, [address_url, src]);

  return (
    <article className={styles.example}>
      <div className={styles.left}>
        <h4>HTML in Markdown</h4>
        <code className={styles.code}>{`<img src="${path}" />`}</code>

        <h4>Markdown</h4>
        <code className={styles.code}>{`![Example button](${path})`}</code>
      </div>
      <aside className={styles.preview}>
        <img src={`/${src}`} alt="Example button" />
      </aside>
    </article>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Github readme buttons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Github readme buttons</h1>

        <p className={styles.description}>
          Use pretty buttons in your github readme files. The buttons are fully
          customisable by an easy-to-use API.
        </p>

        <h1>Basics</h1>
        <p>
          The most basic use case. Just choose the text and implement the tag in
          your MD file. Both of the examples below are usable in your markdown
          file, and both will give you the same result.
        </p>
        <Example src="api/Example" showMD />
      </main>

      <footer className={styles.footer}>
        <a href="https://www.baars.design/">Made with ♥ by baars.design</a>
      </footer>
    </div>
  );
}
